version: 0.2

phases:
  pre_build: 
    commands:
      - echo npm -v
  build:
    commands:
      - echo "It workss!"
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - ls

artifacts:
  files:
    - "**/*"