version: 0.2

phases:
  build:
    commands:
      - echo "It works!"

artifacts:
  files:
    - "**/*"

    aws cloudformation deploy \
  --template-file ecs-pipeline.yml \
  --stack-name example-codepipeline \
  --capabilities CAPABILITY_IAM