version: 0.2

phases:
  install:
    runtime-versions:
      - nodejs: 14.x
    commands:
      - npm install -g typescript
      - npm install
  pre_build: 
    commands:
      - echo npm run test
  build:
    commands:
      - echo "It workss!"
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - ls

artifacts:
  files:
    - "**/*"